language: erlang
install: true
addons:
  apt:
    packages:
    - libsdl2-2.0-0
    - libsdl2-dev
    - libsdl2-gfx-dev
    - libsdl2-image-2.0-0
    - libsdl2-image-dev
    - libsdl2-mixer-2.0-0
    - libsdl2-net-2.0-0
    - libsdl2-net-dev
    - libsdl2-ttf-2.0-0
    - libsdl2-ttf-dev
before_script:
    - wget https://s3.amazonaws.com/rebar3/rebar3
    - chmod +x rebar3
env: PATH=".:$PATH"
script: make compile
otp_release:
  - 18.3
  - 18.0
  - 17.5
  - R16B03-1
  - R15B03
